on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: "${{ github.event.repository.owner.name }}"
      DB_URL: "${{secrets.DB_URL}}"
      JWT_SECRET: "${{secrets.JWT_SECRET}}"
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $DB_URL > .env
          echo $JWT_SECRET >> .env
          git config user.name $REPO_OWNER
          git add -f .env
          git commit --amend --allow-empty-message -m '' --reset-author
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "${{secrets.HEROKU_API_KEY}}"
          heroku_app_name: "${{secrets.HEROKU_APP_NAME}}"
          heroku_email: "${{secrets.HEROKU_EMAIL}}"
